
require('dotenv').config();
const path=require('path'),crypto=require('crypto'),express=require('express'),cors=require('cors'),helmet=require('helmet'),rateLimit=require('express-rate-limit'),sqlite3=require('sqlite3').verbose(),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),QRCode=require('qrcode'),nodemailer=require('nodemailer');
const fs=require('fs'),multer=require('multer');
const app=express(),PORT=process.env.PORT||3000,JWT_SECRET=process.env.JWT_SECRET||'secret',PLATFORM_NAME=process.env.PLATFORM_NAME||'Termini Pro Platforma',DB_PATH=process.env.DB_PATH||path.join(__dirname,'termini-platforma-pro.db');
const UPLOAD_DIR=path.join(__dirname,'public','uploads');
fs.mkdirSync(UPLOAD_DIR,{recursive:true});
const uploadStorage=multer.diskStorage({
 destination:(req,file,cb)=>cb(null,UPLOAD_DIR),
 filename:(req,file,cb)=>{
  let ext=path.extname(file.originalname||'').toLowerCase();
  if(!['.jpg','.jpeg','.png','.webp','.gif'].includes(ext))ext='.jpg';
  cb(null,Date.now()+'-'+crypto.randomBytes(6).toString('hex')+ext);
 }
});
const uploadImage=multer({
 storage:uploadStorage,
 limits:{fileSize:6*1024*1024},
 fileFilter:(req,file,cb)=>{
  if(!/^image\/(jpeg|png|webp|gif)$/i.test(file.mimetype||''))return cb(new Error('Dozvoljene su samo slike JPG, PNG, WEBP ili GIF.'));
  cb(null,true);
 }
});
function oneImage(req,res,next){
 uploadImage.single('image')(req,res,err=>{
  if(err)return res.status(400).json({error:err.message||'Greška pri upload-u slike.'});
  next();
 });
}

app.set('trust proxy',1);app.use(helmet({contentSecurityPolicy:false}));app.use(cors());app.use(express.json({limit:'500kb'}));app.use(express.static(path.join(__dirname,'public')));app.use('/api/',rateLimit({windowMs:15*60*1000,limit:900,standardHeaders:true,legacyHeaders:false}));
const db=new sqlite3.Database(DB_PATH);
const PLANS={basic:{name:'Basic',price:29,max_staff:1,max_month:100,sms:false},standard:{name:'Standard',price:49,max_staff:5,max_month:1000,sms:false},premium:{name:'Premium',price:99,max_staff:30,max_month:10000,sms:true}};
const run=(s,p=[])=>new Promise((res,rej)=>db.run(s,p,function(e){e?rej(e):res(this)}));
const get=(s,p=[])=>new Promise((res,rej)=>db.get(s,p,(e,r)=>e?rej(e):res(r)));
const all=(s,p=[])=>new Promise((res,rej)=>db.all(s,p,(e,r)=>e?rej(e):res(r)));
const clean=(v,n=255)=>String(v||'').trim().slice(0,n),email=v=>clean(v,255).toLowerCase(),phone=v=>String(v||'').replace(/\s+/g,'').slice(0,50),now=()=>new Date().toISOString(),token=()=>crypto.randomBytes(24).toString('hex');
function today(){let d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function addDays(ds,n){let d=new Date(`${ds}T12:00:00`);d.setDate(d.getDate()+n);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
const validDate=d=>/^\d{4}-\d{2}-\d{2}$/.test(String(d||'')),validTime=t=>/^\d{2}:\d{2}$/.test(String(t||'')),tm=t=>{let [h,m]=t.split(':').map(Number);return h*60+m},mt=m=>`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`,dow=d=>new Date(`${d}T12:00:00`).getDay(),over=(a,b,c,d)=>a<d&&c<b;
function slugify(t){const map={'š':'s','đ':'dj','č':'c','ć':'c','ž':'z','Š':'s','Đ':'dj','Č':'c','Ć':'c','Ž':'z'};return String(t||'firma').replace(/[šđčćžŠĐČĆŽ]/g,c=>map[c]||c).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,60)||'firma'}
async function uniqueSlug(n){let b=slugify(n),s=b,i=2;while(await get('SELECT id FROM businesses WHERE slug=?',[s]))s=`${b}-${i++}`;return s}
const abs=(req,p)=>`${req.protocol}://${req.get('host')}${p}`,bookUrl=(req,s)=>abs(req,`/b/${s}`),manageUrl=(req,t)=>abs(req,`/m/${t}`);
function pubBiz(b){return {id:b.id,name:b.name,slug:b.slug,type:b.type||'',city:b.city||'',phone:b.phone||'',instagram:b.instagram||'',address:b.address||'',website:b.website||'',logo_url:b.logo_url||'',cover_url:b.cover_url||'',description:b.description||'',active:b.active,subscription_plan:b.subscription_plan||'basic',subscription_status:b.subscription_status||'trial',subscription_expires_at:b.subscription_expires_at||''}}
function sign(u){return jwt.sign({id:u.id,business_id:u.business_id,name:u.name,email:u.email,role:u.role},JWT_SECRET,{expiresIn:'12h'})}
function auth(req,res,next){let h=req.headers.authorization||'',t=h.startsWith('Bearer ')?h.slice(7):'';if(!t)return res.status(401).json({error:'Moraš biti prijavljen.'});try{req.user=jwt.verify(t,JWT_SECRET);next()}catch{return res.status(401).json({error:'Sesija je istekla.'})}}
const owner=(req,res,next)=>req.user&&req.user.role==='owner'&&req.user.business_id?next():res.status(403).json({error:'Nemaš dozvolu.'});
const superadmin=(req,res,next)=>req.user&&req.user.role==='superadmin'?next():res.status(403).json({error:'Nemaš dozvolu.'});
async function init(){await run('PRAGMA foreign_keys=ON');
 await run(`CREATE TABLE IF NOT EXISTS businesses(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,slug TEXT UNIQUE,type TEXT,city TEXT,phone TEXT,instagram TEXT,address TEXT,website TEXT,logo_url TEXT,cover_url TEXT,description TEXT,active INTEGER DEFAULT 1,subscription_plan TEXT DEFAULT 'basic',subscription_status TEXT DEFAULT 'trial',subscription_expires_at TEXT,google_play_product_id TEXT,google_play_purchase_token TEXT,google_play_order_id TEXT,google_play_state TEXT,google_play_last_check TEXT,created_at TEXT,updated_at TEXT)`);
 await run(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,business_id INTEGER,name TEXT,email TEXT UNIQUE,password_hash TEXT,role TEXT,created_at TEXT)`);
 await run(`CREATE TABLE IF NOT EXISTS settings(business_id INTEGER PRIMARY KEY,interval INTEGER DEFAULT 15,min_notice INTEGER DEFAULT 2,max_days INTEGER DEFAULT 45,notify_customer_email INTEGER DEFAULT 1,notify_owner_email INTEGER DEFAULT 1,notify_sms INTEGER DEFAULT 0,notify_viber INTEGER DEFAULT 0,updated_at TEXT)`);
 await run(`CREATE TABLE IF NOT EXISTS staff(id INTEGER PRIMARY KEY AUTOINCREMENT,business_id INTEGER,name TEXT,title TEXT,phone TEXT,email TEXT,active INTEGER DEFAULT 1,sort_order INTEGER DEFAULT 0,created_at TEXT,updated_at TEXT)`);
 await run(`CREATE TABLE IF NOT EXISTS services(id INTEGER PRIMARY KEY AUTOINCREMENT,business_id INTEGER,name TEXT,description TEXT,duration INTEGER,price INTEGER DEFAULT 0,active INTEGER DEFAULT 1,sort_order INTEGER DEFAULT 0,created_at TEXT,updated_at TEXT)`);
 await run(`CREATE TABLE IF NOT EXISTS hours(business_id INTEGER,day INTEGER,is_open INTEGER,open_time TEXT,close_time TEXT,break_start TEXT,break_end TEXT,PRIMARY KEY(business_id,day))`);
 await run(`CREATE TABLE IF NOT EXISTS blocked(business_id INTEGER,date TEXT,reason TEXT,created_at TEXT,PRIMARY KEY(business_id,date))`);
 await run(`CREATE TABLE IF NOT EXISTS appointments(id INTEGER PRIMARY KEY AUTOINCREMENT,business_id INTEGER,service_id INTEGER,staff_id INTEGER,appt_token TEXT UNIQUE,customer_name TEXT,phone TEXT,email TEXT,date TEXT,start_time TEXT,end_time TEXT,status TEXT DEFAULT 'booked',notes TEXT,created_at TEXT,updated_at TEXT)`);
 await run(`CREATE TABLE IF NOT EXISTS notifications(id INTEGER PRIMARY KEY AUTOINCREMENT,business_id INTEGER,appointment_id INTEGER,channel TEXT,recipient TEXT,subject TEXT,body TEXT,status TEXT,provider TEXT,error TEXT,created_at TEXT)`);
 
 await run(`CREATE TABLE IF NOT EXISTS business_images(id INTEGER PRIMARY KEY AUTOINCREMENT,business_id INTEGER NOT NULL,image_url TEXT NOT NULL,title TEXT DEFAULT '',is_cover INTEGER DEFAULT 0,sort_order INTEGER DEFAULT 0,created_at TEXT,updated_at TEXT)`);
 await run('CREATE INDEX IF NOT EXISTS idx_biz_img ON business_images(business_id)');
 await run('CREATE INDEX IF NOT EXISTS idx_biz_slug ON businesses(slug)');await run('CREATE INDEX IF NOT EXISTS idx_appt_token ON appointments(appt_token)');
 let se=email(process.env.SUPERADMIN_EMAIL||'admin@platform.local');if(!await get('SELECT id FROM users WHERE email=?',[se])){let h=await bcrypt.hash(process.env.SUPERADMIN_PASSWORD||'platform123',12);await run("INSERT INTO users(business_id,name,email,password_hash,role,created_at) VALUES(NULL,'Super Admin',?,?,'superadmin',?)",[se,h,now()])}}
async function defaults(bid,ownerName){await run('INSERT INTO settings(business_id,updated_at) VALUES(?,?)',[bid,now()]);for(let r of [[0,0,'09:00','17:00'],[1,1,'09:00','17:00'],[2,1,'09:00','17:00'],[3,1,'09:00','17:00'],[4,1,'09:00','17:00'],[5,1,'09:00','17:00'],[6,1,'09:00','14:00']])await run('INSERT INTO hours(business_id,day,is_open,open_time,close_time,break_start,break_end) VALUES(?,?,?,?,?,?,?)',[bid,...r,'','']);await run("INSERT INTO staff(business_id,name,title,active,sort_order,created_at,updated_at) VALUES(?,?,'Majstor',1,1,?,?)",[bid,ownerName||'Glavni majstor',now(),now()]);await run("INSERT INTO services(business_id,name,description,duration,price,active,sort_order,created_at,updated_at) VALUES(?,'Osnovna usluga','Promeni naziv i cenu u panelu.',30,1000,1,1,?,?)",[bid,now(),now()])}
async function bizPlanOk(bid){let b=await get('SELECT * FROM businesses WHERE id=?',[bid]);if(!b)return {ok:false,reason:'Firma nije pronađena.'};let st=b.subscription_status||'trial';if(!['trial','active','manual_active'].includes(st))return {ok:false,reason:'Pretplata nije aktivna.'};if(b.subscription_expires_at&&b.subscription_expires_at<today())return {ok:false,reason:'Pretplata je istekla.'};return {ok:true,plan:b.subscription_plan||'basic'}}
async function slots(bid,date,service,staffId=null){if(!(await bizPlanOk(bid)).ok)return[];let s=await get('SELECT * FROM settings WHERE business_id=?',[bid]),t=today(),max=addDays(t,Number(s.max_days||45));if(!validDate(date)||date<t||date>max)return[];if(await get('SELECT 1 FROM blocked WHERE business_id=? AND date=?',[bid,date]))return[];let h=await get('SELECT * FROM hours WHERE business_id=? AND day=?',[bid,dow(date)]);if(!h||!h.is_open)return[];let staff=staffId?[await get('SELECT * FROM staff WHERE business_id=? AND id=? AND active=1',[bid,staffId])]:await all('SELECT * FROM staff WHERE business_id=? AND active=1 ORDER BY sort_order,id',[bid]);staff=staff.filter(Boolean);if(!staff.length)return[];let dur=Number(service.duration),int=Number(s.interval||15),open=tm(h.open_time),close=tm(h.close_time),bs=h.break_start?tm(h.break_start):null,be=h.break_end?tm(h.break_end):null,minDate=new Date(Date.now()+Number(s.min_notice||0)*3600000),out=[];let busy={};for(let st of staff)busy[st.id]=await all("SELECT start_time,end_time FROM appointments WHERE business_id=? AND date=? AND staff_id=? AND status='booked'",[bid,date,st.id]);for(let start=open;start+dur<=close;start+=int){let end=start+dur,stt=mt(start),ett=mt(end);if(new Date(`${date}T${stt}:00`)<minDate)continue;if(bs!==null&&over(start,end,bs,be))continue;for(let p of staff){let c=busy[p.id].some(x=>over(start,end,tm(x.start_time),tm(x.end_time)));if(!c){out.push({start_time:stt,end_time:ett,staff_id:p.id,staff_name:p.name});break}}}return out}
async function nextSlots(bid,from,service,staffId=null){let out=[],st=validDate(from)?from:today();if(st<today())st=today();for(let i=0;i<45&&out.length<5;i++){let d=addDays(st,i);for(let sl of await slots(bid,d,service,staffId)){out.push({date:d,...sl});if(out.length>=5)break}}return out}
async function logN(o){await run('INSERT INTO notifications(business_id,appointment_id,channel,recipient,subject,body,status,provider,error,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)',[o.business_id,o.appointment_id||null,o.channel,o.recipient||'',o.subject||'',o.body||'',o.status||'logged',o.provider||'demo',o.error||'',now()])}
async function sendEmail(o){if(!(process.env.SMTP_HOST&&process.env.SMTP_USER&&process.env.SMTP_PASS))return logN({...o,channel:'email',status:'logged',provider:'smtp-not-configured'});try{let tr=nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:String(process.env.SMTP_SECURE)==='true',auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}});await tr.sendMail({from:process.env.SMTP_FROM||'no-reply@termini.local',to:o.recipient,subject:o.subject,text:o.body});await logN({...o,channel:'email',status:'sent',provider:'smtp'})}catch(e){await logN({...o,channel:'email',status:'failed',provider:'smtp',error:e.message})}}
async function notify(req,a,ctx){let s=await get('SELECT * FROM settings WHERE business_id=?',[a.business_id]),own=await get("SELECT email FROM users WHERE business_id=? AND role='owner' LIMIT 1",[a.business_id]),m=manageUrl(req,a.appt_token);let body=`Termin je zakazan.\nFirma: ${ctx.biz.name}\nUsluga: ${ctx.service.name}\nRadnik: ${ctx.staff.name}\nDatum: ${a.date}\nVreme: ${a.start_time}\nPromena/otkazivanje: ${m}`;let obody=`Novi termin: ${a.customer_name}, ${a.phone}, ${a.date} ${a.start_time}, ${ctx.service.name}, ${ctx.staff.name}`;if(s.notify_customer_email&&a.email)await sendEmail({business_id:a.business_id,appointment_id:a.id,recipient:a.email,subject:'Potvrda termina',body});if(s.notify_owner_email&&own)await sendEmail({business_id:a.business_id,appointment_id:a.id,recipient:own.email,subject:'Novi termin',body:obody});if(s.notify_sms)await logN({business_id:a.business_id,appointment_id:a.id,channel:'sms',recipient:a.phone,subject:'SMS termin',body,status:'logged',provider:process.env.SMS_PROVIDER||'demo'});if(s.notify_viber)await logN({business_id:a.business_id,appointment_id:a.id,channel:'viber',recipient:a.phone,subject:'Viber termin',body,status:'logged',provider:process.env.VIBER_PROVIDER||'demo'})}
app.get('/b/:slug',(req,res)=>res.sendFile(path.join(__dirname,'public','business.html')));app.get('/m/:tok',(req,res)=>res.sendFile(path.join(__dirname,'public','manage.html')));app.get('/api/health',(req,res)=>res.json({ok:true}));app.get('/api/platform',(req,res)=>res.json({name:PLATFORM_NAME,plans:PLANS}));
app.post('/api/auth/register-business',async(req,res)=>{try{let name=clean(req.body.business_name,120),em=email(req.body.email),pw=String(req.body.password||''),ownerName=clean(req.body.owner_name||name,120);if(name.length<2||!em.includes('@')||pw.length<6)return res.status(400).json({error:'Proveri naziv, email i lozinku.'});if(await get('SELECT id FROM users WHERE email=?',[em]))return res.status(409).json({error:'Email već postoji.'});let sl=await uniqueSlug(name),ex=addDays(today(),14),r=await run("INSERT INTO businesses(name,slug,type,city,phone,active,subscription_plan,subscription_status,subscription_expires_at,created_at,updated_at) VALUES(?,?,?,?,?,1,'basic','trial',?,?,?)",[name,sl,clean(req.body.type,80),clean(req.body.city,80),phone(req.body.phone),ex,now(),now()]);let h=await bcrypt.hash(pw,12),ur=await run("INSERT INTO users(business_id,name,email,password_hash,role,created_at) VALUES(?,?,?,?, 'owner',?)",[r.lastID,ownerName,em,h,now()]);await defaults(r.lastID,ownerName);let u={id:ur.lastID,business_id:r.lastID,name:ownerName,email:em,role:'owner'};res.status(201).json({token:sign(u),user:u,business:{id:r.lastID,name,slug:sl},booking_url:bookUrl(req,sl)})}catch(e){res.status(500).json({error:'Greška pri registraciji.'})}});
app.post('/api/auth/login',async(req,res)=>{try{let u=await get('SELECT * FROM users WHERE email=?',[email(req.body.email)]);if(!u||!await bcrypt.compare(String(req.body.password||''),u.password_hash))return res.status(401).json({error:'Pogrešan email ili lozinka.'});res.json({token:sign(u),user:{id:u.id,business_id:u.business_id,name:u.name,email:u.email,role:u.role}})}catch{res.status(500).json({error:'Greška pri prijavi.'})}});
app.get('/api/auth/me',auth,async(req,res)=>{let b=req.user.business_id?await get('SELECT * FROM businesses WHERE id=?',[req.user.business_id]):null;res.json({user:req.user,business:b?{...pubBiz(b),booking_url:bookUrl(req,b.slug)}:null})});
app.get('/api/businesses',async(req,res)=>{let q=clean(req.query.q,100).toLowerCase(),city=clean(req.query.city,80).toLowerCase(),type=clean(req.query.type,80).toLowerCase(),p=[],w='WHERE active=1';if(q){w+=' AND (LOWER(name) LIKE ? OR LOWER(description) LIKE ? OR LOWER(city) LIKE ? OR LOWER(type) LIKE ?)';p.push(`%${q}%`,`%${q}%`,`%${q}%`,`%${q}%`)}if(city){w+=' AND LOWER(city) LIKE ?';p.push(`%${city}%`)}if(type){w+=' AND LOWER(type) LIKE ?';p.push(`%${type}%`)}let rows=await all(`SELECT * FROM businesses ${w} ORDER BY created_at DESC LIMIT 200`,p);res.json(rows.map(b=>({...pubBiz(b),booking_url:bookUrl(req,b.slug)})))});
app.get('/api/businesses/:slug',async(req,res)=>{let b=await get('SELECT * FROM businesses WHERE slug=? AND active=1',[clean(req.params.slug,100)]);if(!b)return res.status(404).json({error:'Firma nije pronađena.'});let ok=await bizPlanOk(b.id);let gallery=await all('SELECT id,image_url,title,is_cover,sort_order FROM business_images WHERE business_id=? ORDER BY is_cover DESC,sort_order,id',[b.id]);let pb=pubBiz(b);let cover=gallery.find(x=>x.is_cover);if(!pb.cover_url&&cover)pb.cover_url=cover.image_url;res.json({business:{...pb,booking_url:bookUrl(req,b.slug)},services:await all('SELECT * FROM services WHERE business_id=? AND active=1 ORDER BY sort_order,id',[b.id]),staff:await all('SELECT id,name,title,phone FROM staff WHERE business_id=? AND active=1 ORDER BY sort_order,id',[b.id]),gallery,settings:await get('SELECT * FROM settings WHERE business_id=?',[b.id]),booking_enabled:ok.ok,booking_disabled_reason:ok.reason||''})});
app.get('/api/businesses/:slug/available-slots',async(req,res)=>{let b=await get('SELECT * FROM businesses WHERE slug=? AND active=1',[clean(req.params.slug,100)]);if(!b)return res.status(404).json({error:'Firma nije pronađena.'});let srv=await get('SELECT * FROM services WHERE business_id=? AND id=? AND active=1',[b.id,Number(req.query.service_id)]);if(!srv)return res.status(404).json({error:'Usluga nije dostupna.'});res.json(await slots(b.id,clean(req.query.date,20),srv,req.query.staff_id?Number(req.query.staff_id):null))});
app.get('/api/businesses/:slug/next-available',async(req,res)=>{let b=await get('SELECT * FROM businesses WHERE slug=? AND active=1',[clean(req.params.slug,100)]);if(!b)return res.status(404).json({error:'Firma nije pronađena.'});let srv=await get('SELECT * FROM services WHERE business_id=? AND id=? AND active=1',[b.id,Number(req.query.service_id)]);if(!srv)return res.status(404).json({error:'Usluga nije dostupna.'});let s=await nextSlots(b.id,clean(req.query.from_date||req.query.date,20),srv,req.query.staff_id?Number(req.query.staff_id):null);res.json({suggestions:s,first_available:s[0]||null})});
app.post('/api/businesses/:slug/appointments',async(req,res)=>{try{let b=await get('SELECT * FROM businesses WHERE slug=? AND active=1',[clean(req.params.slug,100)]);if(!b)return res.status(404).json({error:'Firma nije pronađena.'});let ok=await bizPlanOk(b.id);if(!ok.ok)return res.status(403).json({error:ok.reason});let srv=await get('SELECT * FROM services WHERE business_id=? AND id=? AND active=1',[b.id,Number(req.body.service_id)]);if(!srv)return res.status(404).json({error:'Usluga nije dostupna.'});let ss=await slots(b.id,clean(req.body.date,20),srv,req.body.staff_id?Number(req.body.staff_id):null),sel=ss.find(x=>x.start_time===clean(req.body.start_time,10));if(!sel)return res.status(409).json({error:'Termin više nije slobodan.'});let st=await get('SELECT * FROM staff WHERE id=?',[sel.staff_id]),tok=token();let r=await run("INSERT INTO appointments(business_id,service_id,staff_id,appt_token,customer_name,phone,email,date,start_time,end_time,status,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,'booked',?,?,?)",[b.id,srv.id,sel.staff_id,tok,clean(req.body.customer_name,120),phone(req.body.phone),email(req.body.email),clean(req.body.date,20),sel.start_time,sel.end_time,clean(req.body.notes,500),now(),now()]);let a={id:r.lastID,business_id:b.id,service_id:srv.id,staff_id:sel.staff_id,appt_token:tok,customer_name:clean(req.body.customer_name,120),phone:phone(req.body.phone),email:email(req.body.email),date:clean(req.body.date,20),start_time:sel.start_time,end_time:sel.end_time};await notify(req,a,{biz:b,service:srv,staff:st});res.status(201).json({message:'Termin je zakazan.',manage_url:manageUrl(req,tok),appointment:{...a,service_name:srv.name,staff_name:st.name}})}catch(e){res.status(500).json({error:'Greška pri zakazivanju.'})}});
app.get('/api/manage/:tok',async(req,res)=>{let a=await get(`SELECT a.*,b.name business_name,b.slug business_slug,s.name service_name,s.duration,st.name staff_name FROM appointments a JOIN businesses b ON b.id=a.business_id JOIN services s ON s.id=a.service_id LEFT JOIN staff st ON st.id=a.staff_id WHERE a.appt_token=?`,[clean(req.params.tok,80)]);if(!a)return res.status(404).json({error:'Termin nije pronađen.'});res.json({appointment:a,booking_url:bookUrl(req,a.business_slug)})});
app.get('/api/manage/:tok/available-slots',async(req,res)=>{let a=await get('SELECT * FROM appointments WHERE appt_token=?',[clean(req.params.tok,80)]);if(!a)return res.status(404).json({error:'Termin nije pronađen.'});let srv=await get('SELECT * FROM services WHERE id=?',[a.service_id]);res.json(await slots(a.business_id,clean(req.query.date,20),srv,a.staff_id))});
app.patch('/api/manage/:tok/reschedule',async(req,res)=>{let a=await get('SELECT * FROM appointments WHERE appt_token=?',[clean(req.params.tok,80)]);if(!a||a.status!=='booked')return res.status(400).json({error:'Termin nije aktivan.'});let srv=await get('SELECT * FROM services WHERE id=?',[a.service_id]),ss=await slots(a.business_id,clean(req.body.date,20),srv,req.body.staff_id?Number(req.body.staff_id):a.staff_id),sel=ss.find(x=>x.start_time===clean(req.body.start_time,10));if(!sel)return res.status(409).json({error:'Termin nije slobodan.'});await run('UPDATE appointments SET date=?,start_time=?,end_time=?,staff_id=?,updated_at=? WHERE appt_token=?',[clean(req.body.date,20),sel.start_time,sel.end_time,sel.staff_id,now(),clean(req.params.tok,80)]);await logN({business_id:a.business_id,appointment_id:a.id,channel:'system',subject:'Promena termina',body:`Promenjeno na ${req.body.date} ${sel.start_time}`,status:'logged'});res.json({message:'Termin je promenjen.'})});
app.patch('/api/manage/:tok/cancel',async(req,res)=>{let a=await get('SELECT * FROM appointments WHERE appt_token=?',[clean(req.params.tok,80)]);if(!a||a.status!=='booked')return res.status(400).json({error:'Termin nije aktivan.'});await run("UPDATE appointments SET status='cancelled',notes=notes||?,updated_at=? WHERE appt_token=?",[`\nOtkazano: ${clean(req.body.reason,300)}`,now(),clean(req.params.tok,80)]);await logN({business_id:a.business_id,appointment_id:a.id,channel:'system',subject:'Otkazivanje termina',body:'Termin otkazan preko linka.',status:'logged'});res.json({message:'Termin je otkazan.'})});
app.get('/api/owner/dashboard',auth,owner,async(req,res)=>{let bid=req.user.business_id,b=await get('SELECT * FROM businesses WHERE id=?',[bid]),d=today(),w=addDays(d,7);let cards={today:(await get("SELECT COUNT(*) total FROM appointments WHERE business_id=? AND date=? AND status='booked'",[bid,d])).total,week:(await get("SELECT COUNT(*) total FROM appointments WHERE business_id=? AND date>=? AND date<=? AND status='booked'",[bid,d,w])).total,services:(await get('SELECT COUNT(*) total FROM services WHERE business_id=? AND active=1',[bid])).total,staff:(await get('SELECT COUNT(*) total FROM staff WHERE business_id=? AND active=1',[bid])).total};let upcoming=await all(`SELECT a.*,s.name service_name,st.name staff_name FROM appointments a JOIN services s ON s.id=a.service_id LEFT JOIN staff st ON st.id=a.staff_id WHERE a.business_id=? AND a.date>=? ORDER BY a.date,a.start_time LIMIT 10`,[bid,d]);res.json({business:{...pubBiz(b),booking_url:bookUrl(req,b.slug),plan_limits:PLANS[b.subscription_plan||'basic']},cards,upcoming})});
app.get('/api/owner/qr',auth,owner,async(req,res)=>{let b=await get('SELECT * FROM businesses WHERE id=?',[req.user.business_id]);res.type('image/svg+xml').send(await QRCode.toString(bookUrl(req,b.slug),{type:'svg',margin:1,width:260}))});
app.get('/api/owner/staff',auth,owner,async(req,res)=>res.json(await all('SELECT * FROM staff WHERE business_id=? ORDER BY sort_order,id',[req.user.business_id])));
app.post('/api/owner/staff',auth,owner,async(req,res)=>{let b=await get('SELECT * FROM businesses WHERE id=?',[req.user.business_id]),lim=PLANS[b.subscription_plan||'basic'].max_staff,c=(await get('SELECT COUNT(*) total FROM staff WHERE business_id=? AND active=1',[b.id])).total;if(c>=lim)return res.status(403).json({error:`Paket dozvoljava ${lim} aktivnih radnika.`});let r=await run('INSERT INTO staff(business_id,name,title,phone,email,active,sort_order,created_at,updated_at) VALUES(?,?,?,?,?,1,?,?,?)',[b.id,clean(req.body.name,120),clean(req.body.title,120),phone(req.body.phone),email(req.body.email),Number(req.body.sort_order||0),now(),now()]);res.status(201).json({id:r.lastID,message:'Radnik je dodat.'})});
app.put('/api/owner/staff/:id',auth,owner,async(req,res)=>{await run('UPDATE staff SET name=?,title=?,phone=?,email=?,active=?,sort_order=?,updated_at=? WHERE id=? AND business_id=?',[clean(req.body.name,120),clean(req.body.title,120),phone(req.body.phone),email(req.body.email),req.body.active?1:0,Number(req.body.sort_order||0),now(),Number(req.params.id),req.user.business_id]);res.json({message:'Radnik je sačuvan.'})});
app.get('/api/owner/services',auth,owner,async(req,res)=>res.json(await all('SELECT * FROM services WHERE business_id=? ORDER BY sort_order,id',[req.user.business_id])));
app.post('/api/owner/services',auth,owner,async(req,res)=>{let r=await run('INSERT INTO services(business_id,name,description,duration,price,active,sort_order,created_at,updated_at) VALUES(?,?,?,?,?,1,?,?,?)',[req.user.business_id,clean(req.body.name,120),clean(req.body.description,500),Number(req.body.duration||req.body.duration_minutes||30),Number(req.body.price||0),Number(req.body.sort_order||0),now(),now()]);res.status(201).json({id:r.lastID,message:'Usluga je dodata.'})});
app.put('/api/owner/services/:id',auth,owner,async(req,res)=>{await run('UPDATE services SET name=?,description=?,duration=?,price=?,active=?,sort_order=?,updated_at=? WHERE id=? AND business_id=?',[clean(req.body.name,120),clean(req.body.description,500),Number(req.body.duration||req.body.duration_minutes||30),Number(req.body.price||0),req.body.active?1:0,Number(req.body.sort_order||0),now(),Number(req.params.id),req.user.business_id]);res.json({message:'Usluga je sačuvana.'})});
app.get('/api/owner/appointments',auth,owner,async(req,res)=>{let p=[req.user.business_id,clean(req.query.from,20)||today(),clean(req.query.to,20)||addDays(today(),30)],w='WHERE a.business_id=? AND a.date>=? AND a.date<=?';if(req.query.status){w+=' AND a.status=?';p.push(clean(req.query.status,30))}if(req.query.staff_id){w+=' AND a.staff_id=?';p.push(Number(req.query.staff_id))}res.json(await all(`SELECT a.*,s.name service_name,s.price,st.name staff_name FROM appointments a JOIN services s ON s.id=a.service_id LEFT JOIN staff st ON st.id=a.staff_id ${w} ORDER BY a.date,a.start_time`,p))});
app.patch('/api/owner/appointments/:id/status',auth,owner,async(req,res)=>{await run('UPDATE appointments SET status=?,updated_at=? WHERE id=? AND business_id=?',[clean(req.body.status,30),now(),Number(req.params.id),req.user.business_id]);res.json({message:'Status je promenjen.'})});
app.get('/api/owner/working-hours',auth,owner,async(req,res)=>res.json(await all('SELECT * FROM hours WHERE business_id=? ORDER BY day',[req.user.business_id])));
app.put('/api/owner/working-hours',auth,owner,async(req,res)=>{for(let r of req.body.rows||[])await run('UPDATE hours SET is_open=?,open_time=?,close_time=?,break_start=?,break_end=? WHERE business_id=? AND day=?',[r.is_open?1:0,clean(r.open_time,10),clean(r.close_time,10),clean(r.break_start,10),clean(r.break_end,10),req.user.business_id,Number(r.day)]);res.json({message:'Radno vreme je sačuvano.'})});
app.get('/api/owner/blocked-dates',auth,owner,async(req,res)=>res.json(await all('SELECT * FROM blocked WHERE business_id=? ORDER BY date',[req.user.business_id])));
app.post('/api/owner/blocked-dates',auth,owner,async(req,res)=>{await run('INSERT OR REPLACE INTO blocked(business_id,date,reason,created_at) VALUES(?,?,?,?)',[req.user.business_id,clean(req.body.date,20),clean(req.body.reason,255),now()]);res.status(201).json({message:'Datum je blokiran.'})});
app.delete('/api/owner/blocked-dates/:date',auth,owner,async(req,res)=>{await run('DELETE FROM blocked WHERE business_id=? AND date=?',[req.user.business_id,clean(req.params.date,20)]);res.json({message:'Datum je odblokiran.'})});
app.get('/api/owner/settings',auth,owner,async(req,res)=>{let b=await get('SELECT * FROM businesses WHERE id=?',[req.user.business_id]);res.json({business:{...pubBiz(b),booking_url:bookUrl(req,b.slug)},settings:await get('SELECT * FROM settings WHERE business_id=?',[req.user.business_id]),plans:PLANS})});
app.put('/api/owner/settings',auth,owner,async(req,res)=>{await run('UPDATE businesses SET name=?,type=?,city=?,phone=?,instagram=?,address=?,website=?,logo_url=?,cover_url=?,description=?,updated_at=? WHERE id=?',[clean(req.body.name,120),clean(req.body.type,80),clean(req.body.city,80),phone(req.body.phone),clean(req.body.instagram,120),clean(req.body.address,255),clean(req.body.website,255),clean(req.body.logo_url,500),clean(req.body.cover_url,500),clean(req.body.description,1000),now(),req.user.business_id]);await run('UPDATE settings SET interval=?,min_notice=?,max_days=?,notify_customer_email=?,notify_owner_email=?,notify_sms=?,notify_viber=?,updated_at=? WHERE business_id=?',[Number(req.body.interval||req.body.booking_interval_minutes||15),Number(req.body.min_notice||req.body.min_notice_hours||2),Number(req.body.max_days||req.body.max_booking_days||45),req.body.notify_customer_email?1:0,req.body.notify_owner_email?1:0,req.body.notify_sms?1:0,req.body.notify_viber?1:0,now(),req.user.business_id]);res.json({message:'Podešavanja su sačuvana.'})});
app.get('/api/owner/notifications',auth,owner,async(req,res)=>res.json(await all('SELECT * FROM notifications WHERE business_id=? ORDER BY created_at DESC LIMIT 100',[req.user.business_id])));


app.post('/api/owner/upload-image',auth,owner,oneImage,async(req,res)=>{
 try{
  if(!req.file)return res.status(400).json({error:'Izaberi sliku sa telefona ili računara.'});
  let kind=clean(req.body.kind||req.body.type||'gallery',30);
  let title=clean(req.body.title,120);
  let sort_order=Number(req.body.sort_order||0);
  let image_url='/uploads/'+req.file.filename;
  let is_cover=kind==='cover'||req.body.is_cover==='true'||req.body.is_cover==='1'||req.body.is_cover===true;

  if(kind==='profile'){
   await run('UPDATE businesses SET logo_url=?,updated_at=? WHERE id=?',[image_url,now(),req.user.business_id]);
   return res.json({message:'Profilna slika je postavljena.',image_url});
  }

  if(kind==='cover'){
   await run('UPDATE business_images SET is_cover=0 WHERE business_id=?',[req.user.business_id]);
   await run('UPDATE businesses SET cover_url=?,updated_at=? WHERE id=?',[image_url,now(),req.user.business_id]);
   await run('INSERT INTO business_images(business_id,image_url,title,is_cover,sort_order,created_at,updated_at) VALUES(?,?,?,?,?,?,?)',[req.user.business_id,image_url,title||'Naslovna slika',1,sort_order,now(),now()]);
   return res.json({message:'Naslovna slika je postavljena.',image_url});
  }

  if(is_cover){
   await run('UPDATE business_images SET is_cover=0 WHERE business_id=?',[req.user.business_id]);
   await run('UPDATE businesses SET cover_url=?,updated_at=? WHERE id=?',[image_url,now(),req.user.business_id]);
  }

  let r=await run('INSERT INTO business_images(business_id,image_url,title,is_cover,sort_order,created_at,updated_at) VALUES(?,?,?,?,?,?,?)',[req.user.business_id,image_url,title,is_cover?1:0,sort_order,now(),now()]);
  res.status(201).json({id:r.lastID,message:is_cover?'Slika je dodata u album i postavljena kao naslovna.':'Slika je dodata u album.',image_url});
 }catch(e){
  res.status(500).json({error:'Greška pri upload-u slike.'});
 }
});

app.get('/api/owner/gallery',auth,owner,async(req,res)=>res.json(await all('SELECT * FROM business_images WHERE business_id=? ORDER BY is_cover DESC,sort_order,id',[req.user.business_id])));

app.post('/api/owner/gallery',auth,owner,async(req,res)=>{try{let image_url=clean(req.body.image_url,1000),title=clean(req.body.title,120),sort_order=Number(req.body.sort_order||0),is_cover=req.body.is_cover?1:0;if(!image_url||!/^https?:\/\//i.test(image_url))return res.status(400).json({error:'Unesi URL slike koji počinje sa http ili https.'});if(is_cover){await run('UPDATE business_images SET is_cover=0 WHERE business_id=?',[req.user.business_id]);await run('UPDATE businesses SET cover_url=?,updated_at=? WHERE id=?',[image_url,now(),req.user.business_id])}let r=await run('INSERT INTO business_images(business_id,image_url,title,is_cover,sort_order,created_at,updated_at) VALUES(?,?,?,?,?,?,?)',[req.user.business_id,image_url,title,is_cover,sort_order,now(),now()]);res.status(201).json({id:r.lastID,message:is_cover?'Slika je dodata kao naslovna.':'Slika je dodata u album.'})}catch(e){res.status(500).json({error:'Greška pri dodavanju slike.'})}});

app.put('/api/owner/gallery/:id',auth,owner,async(req,res)=>{try{let id=Number(req.params.id),image_url=clean(req.body.image_url,1000),title=clean(req.body.title,120),sort_order=Number(req.body.sort_order||0),is_cover=req.body.is_cover?1:0;if(!image_url||!/^https?:\/\//i.test(image_url))return res.status(400).json({error:'Unesi URL slike koji počinje sa http ili https.'});let img=await get('SELECT * FROM business_images WHERE id=? AND business_id=?',[id,req.user.business_id]);if(!img)return res.status(404).json({error:'Slika nije pronađena.'});if(is_cover){await run('UPDATE business_images SET is_cover=0 WHERE business_id=?',[req.user.business_id]);await run('UPDATE businesses SET cover_url=?,updated_at=? WHERE id=?',[image_url,now(),req.user.business_id])}await run('UPDATE business_images SET image_url=?,title=?,is_cover=?,sort_order=?,updated_at=? WHERE id=? AND business_id=?',[image_url,title,is_cover,sort_order,now(),id,req.user.business_id]);res.json({message:is_cover?'Slika je sačuvana kao naslovna.':'Slika je sačuvana.'})}catch(e){res.status(500).json({error:'Greška pri čuvanju slike.'})}});

app.patch('/api/owner/gallery/:id/cover',auth,owner,async(req,res)=>{try{let id=Number(req.params.id),img=await get('SELECT * FROM business_images WHERE id=? AND business_id=?',[id,req.user.business_id]);if(!img)return res.status(404).json({error:'Slika nije pronađena.'});await run('UPDATE business_images SET is_cover=0 WHERE business_id=?',[req.user.business_id]);await run('UPDATE business_images SET is_cover=1,updated_at=? WHERE id=? AND business_id=?',[now(),id,req.user.business_id]);await run('UPDATE businesses SET cover_url=?,updated_at=? WHERE id=?',[img.image_url,now(),req.user.business_id]);res.json({message:'Naslovna slika je promenjena.'})}catch(e){res.status(500).json({error:'Greška pri promeni naslovne slike.'})}});

app.delete('/api/owner/gallery/:id',auth,owner,async(req,res)=>{try{let id=Number(req.params.id),img=await get('SELECT * FROM business_images WHERE id=? AND business_id=?',[id,req.user.business_id]);if(!img)return res.status(404).json({error:'Slika nije pronađena.'});await run('DELETE FROM business_images WHERE id=? AND business_id=?',[id,req.user.business_id]);if(img.is_cover){let n=await get('SELECT * FROM business_images WHERE business_id=? ORDER BY sort_order,id LIMIT 1',[req.user.business_id]);if(n){await run('UPDATE business_images SET is_cover=1 WHERE id=?',[n.id]);await run('UPDATE businesses SET cover_url=?,updated_at=? WHERE id=?',[n.image_url,now(),req.user.business_id])}else await run("UPDATE businesses SET cover_url='',updated_at=? WHERE id=?",[now(),req.user.business_id])}res.json({message:'Slika je obrisana.'})}catch(e){res.status(500).json({error:'Greška pri brisanju slike.'})}});
app.get('/api/superadmin/businesses',auth,superadmin,async(req,res)=>{let rows=await all(`SELECT b.*,(SELECT COUNT(*) FROM appointments a WHERE a.business_id=b.id) appointments_count,(SELECT COUNT(*) FROM services s WHERE s.business_id=b.id) services_count,(SELECT COUNT(*) FROM staff st WHERE st.business_id=b.id) staff_count FROM businesses b ORDER BY b.created_at DESC LIMIT 500`);res.json(rows.map(b=>({...pubBiz(b),appointments_count:b.appointments_count,services_count:b.services_count,staff_count:b.staff_count,booking_url:bookUrl(req,b.slug),google_play_product_id:b.google_play_product_id||'',google_play_order_id:b.google_play_order_id||'',google_play_state:b.google_play_state||'',google_play_last_check:b.google_play_last_check||''})))});
app.patch('/api/superadmin/businesses/:id/active',auth,superadmin,async(req,res)=>{await run('UPDATE businesses SET active=?,updated_at=? WHERE id=?',[req.body.active?1:0,now(),Number(req.params.id)]);res.json({message:req.body.active?'Firma je aktivirana.':'Firma je deaktivirana.'})});
app.patch('/api/superadmin/businesses/:id/subscription',auth,superadmin,async(req,res)=>{await run('UPDATE businesses SET subscription_plan=?,subscription_status=?,subscription_expires_at=?,google_play_product_id=?,google_play_order_id=?,google_play_state=?,google_play_last_check=?,updated_at=? WHERE id=?',[clean(req.body.subscription_plan,30),clean(req.body.subscription_status,30),clean(req.body.subscription_expires_at,20),clean(req.body.google_play_product_id,120),clean(req.body.google_play_order_id,120),clean(req.body.google_play_state,120),now(),now(),Number(req.params.id)]);res.json({message:'Pretplata je sačuvana.'})});
app.post('/api/google-play/purchase-token',auth,owner,async(req,res)=>{await run("UPDATE businesses SET google_play_product_id=?,google_play_purchase_token=?,google_play_order_id=?,google_play_state='token_received_pending_verification',google_play_last_check=?,updated_at=? WHERE id=?",[clean(req.body.product_id,120),clean(req.body.purchase_token,500),clean(req.body.order_id,120),now(),now(),req.user.business_id]);res.json({message:'Google Play token je sačuvan. Sledeći korak je verifikacija preko Google Play Developer API-ja.'})});
app.post('/api/google-play/webhook',(req,res)=>{console.log('Google Play RTDN placeholder',JSON.stringify(req.body).slice(0,1000));res.json({ok:true,message:'RTDN primljen. U produkciji se ovde zove Google Play Developer API.'})});
init().then(()=>app.listen(PORT,()=>console.log(`Radi na http://localhost:${PORT}`))).catch(e=>{console.error(e);process.exit(1)});
